
configurePara = struct(...
'inDataDir',  '../../../../AllData/multi_task/datas/',...
'resultDir',  '../../../../AllData/multi_task/results/',...        
...
...
...
'MTRL', struct(...
                   'inDataDir', '../../../../AllData/kMTRL/syn/',...
                   'resultDir', '../../../../AllData/kMTRL/syn/',...
                   'maxIter',     100,...     % outer
                   'tunedParas', struct(...               
                                'lambda1s'  ,  [1e-3,1e-2,1e-1],...
                                'lambda2s' ,   [0,1e-3,1e-2,1e-1,1,10,100,1e+3]... %0,1e-3,1e-2,1e-1,1,10,100,1e+3
                                 )...
                    ),...
'MTRL_Omegatrue', struct(...
                   'inDataDir', '../../../../AllData/kMTRL/syn/',...
                   'resultDir', '../../../../AllData/kMTRL/syn/',...
                   'maxIter',     100,...     % outer
                   'tunedParas', struct(...
                                'lambda1s'  ,  [1e-3,1e-2,1e-1],...
                                'lambda2s' ,   [ 0,1e-3,1e-2,1e-1,1,10,100,1e+3]... %0,1e-3,1e-2,1e-1,1,10,100,1e+3
                                 )...
                    )...                    
);
       
 
                