configurePara = struct(...
'kMTRL_Omega_true',   struct(...
                   'inDataDir', '../../../../AllData/kMTRL/syn/',...
                   'resultDir', '../../../../AllData/kMTRL/syn/',...
                   'maxIter',     5000,...     
                   'tol',         1e-10,...     
                   'Fista_options', struct(...
                                            'bFlag', 0,...
                                            'tFlag', 0,...
                                            'tol',   1e-12,...
                                            'maxIter', 5000 ...
                                            ),...
                   'tunedParas', struct(...
                                'lambda1s'  ,  [0.01],... 
                                'lambda2s' ,   [0.05]... 
                                 )...
                    )...             
);